AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'tmp/**/*'
    - 'db/**/*'
    - 'node_modules/**/*'

# Layout configurations
Layout/LineLength:
  Max: 100
  Exclude:
    - 'test/**/*'

# Style configurations
Style/Documentation:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: single_quotes
  ConsistentQuotesInMultiline: true

Style/SymbolArray:
  EnforcedStyle: percent

Style/WordArray:
  EnforcedStyle: percent

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/ClassAndModuleChildren:
  Enabled: false

# Metrics configurations
Metrics/BlockLength:
  Exclude:
    - 'test/**/*'
    - 'spec/**/*'
    - '*.gemspec'

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'test/**/*'

Metrics/AbcSize:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Metrics/ClassLength:
  Max: 150
  Exclude:
    - 'test/**/*'

# Naming configurations
Naming/MethodParameterName:
  MinNameLength: 2

# Specific gem related configurations
Gemspec/RequiredRubyVersion:
  Enabled: true

# Custom cop configurations
Lint/MissingSuper:
  Exclude:
    - 'lib/todoist/resources/**/*'
